SF_FOOD_TRUCK_SODA_DOMAIN = "data.sfgov.org"
SF_FOOD_TRUCK_SODA_DATASET_ID = "rqzj-sfat"

FOOD_TRUCK_FINDER_SODA_APP_TOKEN = "4yS1K6sN9viNluH6szUqUkGKW"

FOOD_TRUCK_FINDER_SODA_CLIENT = SODA::Client.new({:domain => SF_FOOD_TRUCK_SODA_DOMAIN, :app_token => FOOD_TRUCK_FINDER_SODA_APP_TOKEN})

SF_CENTER_LAT = 37.7833
SF_CENTER_LONG = -122.4167
SF_RADIUS_METERS = 8050

GOOGLE_PLACES_API_KEY = "AIzaSyBCirkyRgWEbWUOEeMWLh93aTfM8cU_8X4"
GOOGLE_PLACES_AUTOCOMPLETE_API_URL = "https://maps.googleapis.com/maps/api/place/autocomplete/json"

